### ISSUE TITLE
meets and joins in a poset

### ISSUE THREAD

**Issue by slwu89** [scheinerman/SimplePosets.jl#10]
Hi @scheinerman how difficult would it be to include functions to compute the meet and join of elements in a poset? We could compute the meet of `n` elements as the largest element in the intersection of their downsets (which we could get with `below`). Likewise for join as the smallest element in intersection of upsets (`above`). So is there an easy way to get the minimum/maximum element(s) for a set of elements?

**Comment by scheinerman** [comment]
There are ways to this, albeit not too efficiently with existing functions. For example, call `above(x)` and `above(y)`, compute the intersection, make an induced poset, and get the minimals. Yeah, that's bad. More significantly the intersection of the upsets of two elements might be empty, or might have multiple minimals, so there wouldn't be a unique join (or meet).

**Comment by slwu89** [comment]
Thanks for the swift reply @scheinerman! Yeah, the inefficient "algorithm" mentioned above will work fine for now, as in my immediate use case, I'll be able to be guaranteed unique joins/meets.

I'm no mathematician but I can see what you mean by the general problem of posets which might not have meets/joins, or not unique ones. I guess in the case where there did not exist unique meets/joins you would need a way to store isomorphism classes.
