### ISSUE TITLE
Error loading SimplePosets

### ISSUE THREAD

**Issue by sethaxen** [scheinerman/SimplePosets.jl#6]
I am loading a package that depends on both SimplePosets and SimpleGraphs (constrained to v0.7.18). The most recent SimplePosets version with this SimpleGraphs compatibility was v0.1.6, so that is loaded by the dependency. Then I get the following error:

```julia
      From worker 2:	ERROR: LoadError: UndefVarError: DG not defined
      From worker 2:	Stacktrace:
      From worker 2:	 [1] top-level scope
      From worker 2:	   @ ~/.julia/packages/SimplePosets/TCRKU/src/SimplePosets.jl:29
      From worker 2:	 [2] include
      From worker 2:	   @ ./Base.jl:418 [inlined]
      From worker 2:	 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
      From worker 2:	   @ Base./loading.jl:1318
      From worker 2:	 [4] top-level scope
      From worker 2:	   @ none:1
      From worker 2:	 [5] eval
      From worker 2:	   @ ./boot.jl:373 [inlined]
      From worker 2:	 [6] eval(x::Expr)
      From worker 2:	   @ Base.MainInclude./client.jl:453
      From worker 2:	 [7] top-level scope
      From worker 2:	   @ none:1
      From worker 2:	in expression starting at /home/runner/.julia/packages/SimplePosets/TCRKU/src/SimplePosets.jl:1
```

This seems to be happening because v0.1.6 started using the const `DG`, which is only present in `v0.8` of SimpleGraphs, but the necessary version bound of SimpleGraphs was not added to SimplePosets until v0.1.7.

**Comment by scheinerman** [comment]
Do I need to update the version numbers of packages that depend on `SimpleGraphs`? This sort of stuff really confuses me!

**Comment by sethaxen** [comment]
If a dependant of SimpleGraphs has a lower bound of v0.X.Y of SimpleGraphs and starts using a feature introduced in version v0.Z.W where v0.Z.W > v0.X.Y, then the lower bound must be updated to v0.Z.W.

Not updating the lower bound probably won't cause problems when Z=X, since by semvar, there are no breaking changes from v0.X.Y to v0.Z.W, and Pkg will probably update 0.X.Y to 0.Z.W transparently. But if Z > X, so the change is breaking, then not updating the version bound means the dependant will now error if for any reason something in their environment prevents the update to v0.Z.W.

So v0.1.6 of this package, which started using the `DG` constant introduced in v0.8.0 of SimpleGraphs, needed to update its compat entry for SimpleGraphs to v0.8.0.

https://github.com/SciML/ColPrac#accidental-breaking-releases might be helpful advice for how to repair this.

**Comment by scheinerman** [comment]
I looked at my `Project.toml` file and the `[compat]` section has the line 
```
SimpleGraphs = "0.8"
```
Should I re-release this as version `0.2.0` (instead of `0.1.7` which is where I am now)? 

Sorry, I'm confused by all this!
